#### Loading libraries needed ####
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("xml2")) install.packages("xml2")
if (!require("XML")) install.packages("XML")
if (!require("RSelenium")) install.packages("RSelenium")
if (!require("readxl")) install.packages("readxl")
if (!require("scholar")) install.packages("scholar")
if (!require("rvest")) install.packages("rvest")
if (!require("miceadds")) install.packages("miceadds")
if (!require("pbdZMQ")) install.packages("pbdZMQ")
if (!require("matrixStats")) install.packages("matrixStats")
if (!require("caret")) install.packages("caret")
if (!require("elasticnet")) install.packages("elasticnet")
if (!require("kernlab")) install.packages("kernlab")
if (!require("randomForest")) install.packages("randomForest")
if (!require("keras")) install.packages("keras")
if (!require("tensorflow")) install.packages("tensorflow")
if (!require("magrittr")) install.packages("magrittr")
if (!require("reticulate")) install.packages("reticulate")
if (!require("viridis")) install.packages("viridis")
if (!require("ggsci")) install.packages("ggsci")
if (!require("xgboost")) install.packages("xgboost")
if (!require("vtable")) install.packages("vtable")
if (!require("ggpubr")) install.packages("ggpubr")
if (!require("ggtext")) install.packages("ggtext")
if (!require("gridtext")) install.packages("gridtext")
if (!require("grid")) install.packages("grid")
if (!require("gridExtra")) install.packages("gridExtra")

library(tidyverse)
library(xml2)
library(XML)
library(RSelenium)
library(readxl)
library(scholar)
library(rvest)
library(miceadds)
library(pbdZMQ)
library(matrixStats)
library(caret)
library(elasticnet)
library(kernlab)
library(randomForest)
library(keras)
library(tensorflow)
library(magrittr)
library(reticulate)
library(viridis)
library(ggsci)
library(xgboost)
library(vtable)
library(ggpubr)
library(ggtext)
library(gridtext)
library(grid)
library(gridExtra)

# Source all R-files in the Functions folder
source.all("function/", grepstring="\\.R")


